//
//  HangerHelpServiceIntegrationTests.swift
//  BuzzTests
//
//  Integration tests for HangerHelpService calling real Supabase.
//  Creates posts, comments, and interactions against live DB, then
//  cleans up in tearDown.
//

import XCTest
import Supabase
@testable import Buzz

@MainActor
final class HangerHelpServiceIntegrationTests: IntegrationTestCase {

    private var service: HangerHelpService!

    /// The first active topic fetched from the DB (used to create test posts).
    private var testTopicId: UUID!

    override func setUp() async throws {
        try await super.setUp()
        service = HangerHelpService()

        // Fetch topics so we have a valid topic ID for creating posts
        await service.fetchTopics()
        guard let firstTopic = service.topics.first else {
            XCTFail("No active topics found in the database – seed hanger_topics first")
            return
        }
        testTopicId = firstTopic.id
    }

    override func tearDown() async throws {
        service = nil
        testTopicId = nil
        try await super.tearDown()
    }

    // MARK: - Helper: Create a post and track for cleanup

    @discardableResult
    private func createTestPost(
        title: String = "Integration Test Post",
        body: String = "Auto-generated by integration test"
    ) async throws -> UUID {
        try await service.createPost(
            topicId: testTopicId,
            authorId: TestUser.id,
            title: title,
            body: body
        )

        // Fetch posts to find the one we just created
        await service.fetchAllPosts(currentUserId: TestUser.id)
        guard let created = service.posts.first(where: { $0.post.title == title }) else {
            XCTFail("Created post '\(title)' not found after fetch")
            return UUID()
        }

        trackForCleanup(table: "hanger_posts", id: created.id)
        return created.id
    }

    @discardableResult
    private func createTestComment(
        postId: UUID,
        body: String = "Integration test comment",
        parentCommentId: UUID? = nil,
        depth: Int = 0
    ) async throws -> UUID {
        try await service.createComment(
            postId: postId,
            parentCommentId: parentCommentId,
            authorId: TestUser.id,
            body: body,
            depth: depth
        )

        // Fetch comments to find the one we just created
        await service.fetchComments(postId: postId, currentUserId: TestUser.id)
        guard let created = findComment(body: body, in: service.comments) else {
            XCTFail("Created comment '\(body)' not found after fetch")
            return UUID()
        }

        trackForCleanup(table: "hanger_comments", id: created.id)
        return created.id
    }

    /// Recursively searches the comment tree for a comment with the given body.
    private func findComment(body: String, in comments: [HangerCommentWithAuthor]) -> HangerCommentWithAuthor? {
        for comment in comments {
            if comment.comment.body == body {
                return comment
            }
            if let found = findComment(body: body, in: comment.replies) {
                return found
            }
        }
        return nil
    }

    // MARK: - Topics

    func testFetchTopics_returnsActiveTopics() async {
        await service.fetchTopics()

        XCTAssertFalse(service.topics.isEmpty, "Should return at least one topic")
        XCTAssertNil(service.errorMessage)
        XCTAssertFalse(service.isLoading)

        // All topics should be active
        for topic in service.topics {
            XCTAssertTrue(topic.isActive)
        }

        // Should be sorted by display_order
        let orders = service.topics.map(\.displayOrder)
        XCTAssertEqual(orders, orders.sorted(), "Topics should be sorted by display_order")
    }

    func testFetchTopics_containsExpectedNames() async {
        await service.fetchTopics()

        let names = Set(service.topics.map(\.name))
        for expected in HangerTestData.allTopicNames {
            XCTAssertTrue(names.contains(expected), "Missing expected topic: \(expected)")
        }
    }

    // MARK: - Create & Fetch Posts

    func testCreatePost_insertsAndFetches() async throws {
        let postId = try await createTestPost(
            title: "Create Post Integration",
            body: "Verifying round-trip"
        )

        let match = service.posts.first { $0.id == postId }
        XCTAssertNotNil(match)
        XCTAssertEqual(match?.post.title, "Create Post Integration")
        XCTAssertEqual(match?.post.body, "Verifying round-trip")
        XCTAssertEqual(match?.post.authorId, TestUser.id)
    }

    func testCreatePost_defaultsToZeroCounts() async throws {
        let postId = try await createTestPost(title: "Zero Counts Test")

        let match = service.posts.first { $0.id == postId }
        XCTAssertEqual(match?.post.likeCount, 0)
        XCTAssertEqual(match?.post.commentCount, 0)
        XCTAssertFalse(match?.post.isPinned ?? true)
    }

    func testCreatePost_withImageUrls() async throws {
        let urls = ["https://example.com/test1.jpg", "https://example.com/test2.jpg"]
        try await service.createPost(
            topicId: testTopicId,
            authorId: TestUser.id,
            title: "Image URLs Post",
            body: "Has images",
            imageUrls: urls
        )

        await service.fetchAllPosts(currentUserId: TestUser.id)
        guard let match = service.posts.first(where: { $0.post.title == "Image URLs Post" }) else {
            XCTFail("Post with images not found")
            return
        }
        trackForCleanup(table: "hanger_posts", id: match.id)

        XCTAssertEqual(match.imageUrls.count, 2)
        XCTAssertEqual(match.imageUrls, urls)
    }

    // MARK: - Fetch Posts for Topic

    func testFetchPostsForTopic_filtersCorrectly() async throws {
        let postId = try await createTestPost(title: "Topic Filter Test")

        await service.fetchPosts(topicId: testTopicId, currentUserId: TestUser.id)

        let match = service.posts.first { $0.id == postId }
        XCTAssertNotNil(match, "Post should appear in its topic's feed")

        // All posts in the result should belong to the topic
        for post in service.posts {
            XCTAssertEqual(post.post.topicId, testTopicId)
        }
    }

    // MARK: - Update Post

    func testUpdatePost_changesFields() async throws {
        let postId = try await createTestPost(title: "Before Update", body: "Original body")

        try await service.updatePost(postId: postId, title: "After Update", body: "Updated body")

        // Re-fetch to verify
        await service.fetchAllPosts(currentUserId: TestUser.id)
        let match = service.posts.first { $0.id == postId }
        XCTAssertEqual(match?.post.title, "After Update")
        XCTAssertEqual(match?.post.body, "Updated body")
    }

    // MARK: - Delete Post

    func testDeletePost_removesFromFeed() async throws {
        let postId = try await createTestPost(title: "To Be Deleted")

        try await service.deletePost(postId: postId)

        // Re-fetch and verify it's gone
        await service.fetchAllPosts(currentUserId: TestUser.id)
        let match = service.posts.first { $0.id == postId }
        XCTAssertNil(match, "Deleted post should not appear in feed")
    }

    // MARK: - Create & Fetch Comments

    func testCreateComment_insertsAndFetches() async throws {
        let postId = try await createTestPost(title: "Comment Parent Post")
        let commentId = try await createTestComment(postId: postId, body: "Hello from test!")

        let match = findComment(body: "Hello from test!", in: service.comments)
        XCTAssertNotNil(match)
        XCTAssertEqual(match?.id, commentId)
        XCTAssertEqual(match?.comment.depth, 0)
        XCTAssertNil(match?.comment.parentCommentId)
    }

    func testNestedComment_appearsAsReply() async throws {
        let postId = try await createTestPost(title: "Nested Comment Post")
        let parentId = try await createTestComment(postId: postId, body: "Parent comment", depth: 0)
        let childId = try await createTestComment(
            postId: postId,
            body: "Child reply",
            parentCommentId: parentId,
            depth: 1
        )

        // Re-fetch comments to build the tree
        await service.fetchComments(postId: postId, currentUserId: TestUser.id)

        // Find parent in top-level
        let parent = service.comments.first { $0.id == parentId }
        XCTAssertNotNil(parent, "Parent comment should be in top-level")

        // Child should be in parent's replies
        let child = parent?.replies.first { $0.id == childId }
        XCTAssertNotNil(child, "Child reply should be nested under parent")
        XCTAssertEqual(child?.comment.body, "Child reply")
        XCTAssertEqual(child?.comment.depth, 1)
    }

    // MARK: - Update Comment

    func testUpdateComment_changesBody() async throws {
        let postId = try await createTestPost(title: "Update Comment Post")
        let commentId = try await createTestComment(postId: postId, body: "Original comment")

        try await service.updateComment(commentId: commentId, body: "Edited comment")

        await service.fetchComments(postId: postId, currentUserId: TestUser.id)
        let match = findComment(body: "Edited comment", in: service.comments)
        XCTAssertNotNil(match, "Comment body should be updated")
        XCTAssertEqual(match?.id, commentId)
    }

    // MARK: - Delete Comment

    func testDeleteComment_removesFromTree() async throws {
        let postId = try await createTestPost(title: "Delete Comment Post")
        let commentId = try await createTestComment(postId: postId, body: "Comment to delete")

        try await service.deleteComment(commentId: commentId)

        await service.fetchComments(postId: postId, currentUserId: TestUser.id)
        let match = findComment(body: "Comment to delete", in: service.comments)
        XCTAssertNil(match, "Deleted comment should not appear")
    }

    // MARK: - Toggle Post Like

    func testTogglePostLike_addsAndRemoves() async throws {
        let postId = try await createTestPost(title: "Like Toggle Post")

        // Like the post
        try await service.togglePostLike(postId: postId, userId: TestUser.id)

        // Verify liked state
        await service.fetchAllPosts(currentUserId: TestUser.id)
        var match = service.posts.first { $0.id == postId }
        XCTAssertTrue(match?.isLikedByCurrentUser ?? false, "Post should be liked")

        // Clean up the like (also verifies unlike works)
        try await service.togglePostLike(postId: postId, userId: TestUser.id)

        await service.fetchAllPosts(currentUserId: TestUser.id)
        match = service.posts.first { $0.id == postId }
        XCTAssertFalse(match?.isLikedByCurrentUser ?? true, "Post should be unliked")
    }

    // MARK: - Toggle Comment Like

    func testToggleCommentLike_addsAndRemoves() async throws {
        let postId = try await createTestPost(title: "Comment Like Post")
        let commentId = try await createTestComment(postId: postId, body: "Likeable comment")

        // Like the comment
        try await service.toggleCommentLike(commentId: commentId, userId: TestUser.id)

        // Verify liked state
        await service.fetchComments(postId: postId, currentUserId: TestUser.id)
        var match = findComment(body: "Likeable comment", in: service.comments)
        XCTAssertTrue(match?.isLikedByCurrentUser ?? false, "Comment should be liked")

        // Unlike
        try await service.toggleCommentLike(commentId: commentId, userId: TestUser.id)

        await service.fetchComments(postId: postId, currentUserId: TestUser.id)
        match = findComment(body: "Likeable comment", in: service.comments)
        XCTAssertFalse(match?.isLikedByCurrentUser ?? true, "Comment should be unliked")
    }

    // MARK: - Toggle Save Post

    func testToggleSavePost_addsAndRemoves() async throws {
        let postId = try await createTestPost(title: "Save Toggle Post")

        // Save the post
        try await service.toggleSavePost(postId: postId, userId: TestUser.id)

        // Verify saved state
        await service.fetchAllPosts(currentUserId: TestUser.id)
        var match = service.posts.first { $0.id == postId }
        XCTAssertTrue(match?.isSavedByCurrentUser ?? false, "Post should be saved")

        // Verify it appears in saved posts
        await service.fetchSavedPosts(currentUserId: TestUser.id)
        XCTAssertTrue(service.savedPosts.contains { $0.id == postId }, "Post should appear in saved list")

        // Unsave
        try await service.toggleSavePost(postId: postId, userId: TestUser.id)

        await service.fetchAllPosts(currentUserId: TestUser.id)
        match = service.posts.first { $0.id == postId }
        XCTAssertFalse(match?.isSavedByCurrentUser ?? true, "Post should be unsaved")

        // Verify it no longer appears in saved posts
        await service.fetchSavedPosts(currentUserId: TestUser.id)
        XCTAssertFalse(service.savedPosts.contains { $0.id == postId }, "Post should not appear in saved list")
    }

    // MARK: - Toggle Follow Post

    func testToggleFollowPost_addsAndRemoves() async throws {
        let postId = try await createTestPost(title: "Follow Toggle Post")

        // Follow the post
        try await service.toggleFollowPost(postId: postId, userId: TestUser.id)

        await service.fetchAllPosts(currentUserId: TestUser.id)
        var match = service.posts.first { $0.id == postId }
        XCTAssertTrue(match?.isFollowedByCurrentUser ?? false, "Post should be followed")

        // Unfollow
        try await service.toggleFollowPost(postId: postId, userId: TestUser.id)

        await service.fetchAllPosts(currentUserId: TestUser.id)
        match = service.posts.first { $0.id == postId }
        XCTAssertFalse(match?.isFollowedByCurrentUser ?? true, "Post should be unfollowed")
    }

    // MARK: - Toggle Hide Post

    func testToggleHidePost_addsAndRemoves() async throws {
        let postId = try await createTestPost(title: "Hide Toggle Post")

        // Hide the post
        try await service.toggleHidePost(postId: postId, userId: TestUser.id)
        XCTAssertTrue(service.hiddenPostIds.contains(postId), "Post should be in hidden set")

        // Unhide
        try await service.toggleHidePost(postId: postId, userId: TestUser.id)
        XCTAssertFalse(service.hiddenPostIds.contains(postId), "Post should be removed from hidden set")
    }

    // MARK: - Toggle Save Comment

    func testToggleSaveComment_addsAndRemoves() async throws {
        let postId = try await createTestPost(title: "Save Comment Post")
        let commentId = try await createTestComment(postId: postId, body: "Saveable comment")

        // Save the comment
        try await service.toggleSaveComment(commentId: commentId, userId: TestUser.id)

        // Verify saved comments list
        await service.fetchSavedComments(currentUserId: TestUser.id)
        XCTAssertTrue(service.savedComments.contains { $0.id == commentId }, "Comment should appear in saved list")

        // Unsave
        try await service.toggleSaveComment(commentId: commentId, userId: TestUser.id)

        await service.fetchSavedComments(currentUserId: TestUser.id)
        XCTAssertFalse(service.savedComments.contains { $0.id == commentId }, "Comment should not appear in saved list")
    }

    // MARK: - Toggle Follow Comment

    func testToggleFollowComment_addsAndRemoves() async throws {
        let postId = try await createTestPost(title: "Follow Comment Post")
        let commentId = try await createTestComment(postId: postId, body: "Followable comment")

        // Follow the comment
        try await service.toggleFollowComment(commentId: commentId, userId: TestUser.id)

        // We can verify by checking Supabase directly
        let follows: [HangerFollowedComment] = try await supabase
            .from("hanger_followed_comments")
            .select()
            .eq("user_id", value: TestUser.id.uuidString)
            .eq("comment_id", value: commentId.uuidString)
            .execute()
            .value
        XCTAssertEqual(follows.count, 1, "Comment should have a follow record")

        // Unfollow
        try await service.toggleFollowComment(commentId: commentId, userId: TestUser.id)

        let followsAfter: [HangerFollowedComment] = try await supabase
            .from("hanger_followed_comments")
            .select()
            .eq("user_id", value: TestUser.id.uuidString)
            .eq("comment_id", value: commentId.uuidString)
            .execute()
            .value
        XCTAssertTrue(followsAfter.isEmpty, "Follow record should be removed")
    }

    // MARK: - Fetch Saved Posts (empty)

    func testFetchSavedPosts_emptyWhenNoneSaved() async {
        await service.fetchSavedPosts(currentUserId: TestUser.id)
        // May or may not be empty depending on test state, but should not error
        XCTAssertNil(service.errorMessage)
    }

    // MARK: - Fetch Saved Comments (empty)

    func testFetchSavedComments_emptyWhenNoneSaved() async {
        await service.fetchSavedComments(currentUserId: TestUser.id)
        XCTAssertNil(service.errorMessage)
    }

    // MARK: - Activity

    func testFetchActivityItems_noErrorWhenEmpty() async {
        await service.fetchActivityItems(currentUserId: TestUser.id)
        // Should complete without error
        XCTAssertNil(service.errorMessage)
    }

    func testCheckForNewActivity_setsFlag() async {
        await service.checkForNewActivity(currentUserId: TestUser.id)
        // Should complete without error (flag depends on test state)
        XCTAssertNil(service.errorMessage)
    }

    // MARK: - Post With Author Topic Info

    func testPostWithAuthor_includesTopicInfo() async throws {
        let postId = try await createTestPost(title: "Topic Info Post")

        let match = service.posts.first { $0.id == postId }
        XCTAssertNotNil(match?.topicName, "Should have topic name")
        XCTAssertFalse(match?.topicName.isEmpty ?? true, "Topic name should not be empty")
        XCTAssertNotNil(match?.topicIconName, "Should have topic icon name")
        XCTAssertNotNil(match?.topicColorName, "Should have topic color name")
    }

    // MARK: - Post With Author Profile Info

    func testPostWithAuthor_includesAuthorInfo() async throws {
        let postId = try await createTestPost(title: "Author Info Post")

        let match = service.posts.first { $0.id == postId }
        XCTAssertNotNil(match)
        XCTAssertFalse(match?.authorFullName.isEmpty ?? true, "Should have author full name")
    }

    // MARK: - Multiple Interactions on Same Post

    func testMultipleInteractions_coexist() async throws {
        let postId = try await createTestPost(title: "Multi Interaction Post")

        // Like + Save + Follow the same post
        try await service.togglePostLike(postId: postId, userId: TestUser.id)
        try await service.toggleSavePost(postId: postId, userId: TestUser.id)
        try await service.toggleFollowPost(postId: postId, userId: TestUser.id)

        await service.fetchAllPosts(currentUserId: TestUser.id)
        let match = service.posts.first { $0.id == postId }
        XCTAssertTrue(match?.isLikedByCurrentUser ?? false)
        XCTAssertTrue(match?.isSavedByCurrentUser ?? false)
        XCTAssertTrue(match?.isFollowedByCurrentUser ?? false)

        // Clean up all interactions
        try await service.togglePostLike(postId: postId, userId: TestUser.id)
        try await service.toggleSavePost(postId: postId, userId: TestUser.id)
        try await service.toggleFollowPost(postId: postId, userId: TestUser.id)
    }
}
