//
//  MarketplaceIntegrationTests.swift
//  BuzzTests
//
//  Integration tests for MarketplaceService calling real Supabase.
//  Tests CRUD operations, state transitions, and RLS policy verification.
//

import XCTest
import Supabase
@testable import Buzz

@MainActor
final class MarketplaceIntegrationTests: IntegrationTestCase {

    private var service: MarketplaceService!

    override func setUp() async throws {
        try await super.setUp()
        service = MarketplaceService()
    }

    override func tearDown() async throws {
        service = nil
        try await super.tearDown()
    }

    // MARK: - Helpers

    /// Creates a listing owned by the test user and tracks it for cleanup.
    @discardableResult
    private func createTestListing(
        title: String = "Integration Test Drone",
        description: String = "Auto-generated by integration test",
        price: Decimal = 299.99,
        category: MarketplaceCategory = .drones,
        condition: ListingCondition = .good,
        transactionType: MarketplaceTransactionType = .both
    ) async throws -> MarketplaceListing {
        let insert = MarketplaceListingInsert(
            sellerId: TestUser.id,
            title: title,
            description: description,
            price: price,
            category: category,
            condition: condition,
            transactionType: transactionType,
            imageUrls: ["https://example.com/test-drone.jpg"],
            locationName: "Test Location, CA",
            locationLat: 37.7749,
            locationLng: -122.4194,
            brand: "TestBrand",
            model: "TestModel",
            shippingCost: 10.00
        )

        let listing = try await service.createListing(insert: insert)
        trackForCleanup(table: "marketplace_listings", id: listing.id)
        return listing
    }

    /// Creates an offer by the test user on a listing and tracks it for cleanup.
    @discardableResult
    private func createTestOffer(
        listingId: UUID,
        amount: Decimal = 250.00,
        message: String? = "Integration test offer"
    ) async throws -> UUID {
        try await service.createOffer(
            listingId: listingId,
            buyerId: TestUser.id,
            amount: amount,
            message: message
        )

        // Fetch offers to find the one we just created
        await service.fetchOffersForListing(listingId: listingId)
        guard let offer = service.offers.first(where: {
            $0.amount == amount && $0.message == message
        }) else {
            XCTFail("Created offer not found after fetch")
            return UUID()
        }

        trackForCleanup(table: "marketplace_offers", id: offer.id)
        return offer.id
    }

    /// Creates a ship transaction with test user as seller.
    /// Returns nil and calls XCTSkip if RLS blocks the insert.
    @discardableResult
    private func createTestShipTransaction(
        listingId: UUID,
        amount: Decimal = 300,
        buyerId: UUID = UUID()
    ) async throws -> MarketplaceTransaction {
        let transaction = try await service.createShipTransaction(
            listingId: listingId,
            buyerId: buyerId,
            sellerId: TestUser.id,
            offerId: nil,
            amount: amount
        )
        trackForCleanup(table: "marketplace_transactions", id: transaction.id)
        return transaction
    }

    // MARK: - Listing Lifecycle

    func testCreateAndFetchListing() async throws {
        let listing = try await createTestListing(
            title: "Create Fetch Test Drone",
            description: "Round-trip verification",
            price: 499.99,
            category: .drones,
            condition: .likeNew
        )

        XCTAssertEqual(listing.sellerId, TestUser.id)
        XCTAssertEqual(listing.title, "Create Fetch Test Drone")
        XCTAssertEqual(listing.description, "Round-trip verification")
        XCTAssertEqual(listing.price, 499.99)
        XCTAssertEqual(listing.category, .drones)
        XCTAssertEqual(listing.condition, .likeNew)
        XCTAssertEqual(listing.status, .active)
        XCTAssertEqual(listing.brand, "TestBrand")
        XCTAssertEqual(listing.model, "TestModel")

        // Fetch it back via the service
        let fetched = await service.fetchListingDetail(
            listingId: listing.id,
            currentUserId: TestUser.id
        )
        XCTAssertNotNil(fetched)
        XCTAssertEqual(fetched?.listing.id, listing.id)
        XCTAssertEqual(fetched?.listing.title, "Create Fetch Test Drone")
        XCTAssertEqual(fetched?.listing.price, 499.99)
        XCTAssertFalse(fetched?.sellerFullName.isEmpty ?? true, "Should have seller name from profile join")
    }

    func testUpdateListing() async throws {
        let listing = try await createTestListing(title: "Before Update", price: 100)

        var updates = MarketplaceListingUpdate()
        updates.title = "After Update"
        updates.price = 150

        try await service.updateListing(listingId: listing.id, updates: updates)

        // Re-fetch to verify
        let fetched = await service.fetchListingDetail(
            listingId: listing.id,
            currentUserId: TestUser.id
        )
        XCTAssertEqual(fetched?.listing.title, "After Update")
        XCTAssertEqual(fetched?.listing.price, 150)
        // Unchanged fields should be preserved
        XCTAssertEqual(fetched?.listing.category, .drones)
    }

    func testDeleteListing() async throws {
        let listing = try await createTestListing(title: "To Be Deleted")

        try await service.deleteListing(listingId: listing.id)

        let fetched = await service.fetchListingDetail(
            listingId: listing.id,
            currentUserId: TestUser.id
        )
        XCTAssertNil(fetched, "Deleted listing should not be fetchable")
    }

    func testFetchListings_filterByCategory() async throws {
        let droneListing = try await createTestListing(
            title: "Category Filter Drone",
            category: .drones
        )
        let batteryListing = try await createTestListing(
            title: "Category Filter Battery",
            category: .batteries
        )

        await service.fetchListings(category: .drones, currentUserId: TestUser.id)

        let droneFound = service.listings.contains { $0.listing.id == droneListing.id }
        XCTAssertTrue(droneFound, "Drone listing should appear in drones category filter")

        let batteryFound = service.listings.contains { $0.listing.id == batteryListing.id }
        XCTAssertFalse(batteryFound, "Battery listing should NOT appear in drones category filter")
    }

    func testFetchListings_searchByTitle() async throws {
        let listing = try await createTestListing(
            title: "UniqueSearchXK9000 Drone"
        )

        await service.fetchListings(searchQuery: "XK9000", currentUserId: TestUser.id)

        let found = service.listings.contains { $0.listing.id == listing.id }
        XCTAssertTrue(found, "Listing should be found by partial title search")
    }

    // MARK: - Favorites

    func testToggleFavorite_addAndRemove() async throws {
        let listing = try await createTestListing(title: "Favorite Toggle Listing")

        // Add favorite
        try await service.toggleFavorite(listingId: listing.id, userId: TestUser.id)

        await service.fetchFavorites(userId: TestUser.id)
        XCTAssertTrue(
            service.favoriteListings.contains { $0.listing.id == listing.id },
            "Listing should be in favorites after adding"
        )

        // Remove favorite
        try await service.toggleFavorite(listingId: listing.id, userId: TestUser.id)

        await service.fetchFavorites(userId: TestUser.id)
        XCTAssertFalse(
            service.favoriteListings.contains { $0.listing.id == listing.id },
            "Listing should NOT be in favorites after removing"
        )
    }

    // MARK: - Offers

    func testCreateAndFetchOffer() async throws {
        let listing = try await createTestListing(title: "Offer Test Listing")

        let offerId = try await createTestOffer(
            listingId: listing.id,
            amount: 275.00,
            message: "Would you accept $275?"
        )

        let match = service.offers.first { $0.id == offerId }
        XCTAssertNotNil(match)
        XCTAssertEqual(match?.amount, 275.00)
        XCTAssertEqual(match?.message, "Would you accept $275?")
        XCTAssertEqual(match?.status, .pending)
        XCTAssertEqual(match?.buyerId, TestUser.id)
    }

    func testAcceptOffer() async throws {
        let listing = try await createTestListing(title: "Accept Offer Listing")
        let offerId = try await createTestOffer(listingId: listing.id, amount: 200)

        // Ensure offers are in the service's local cache
        await service.fetchOffersForListing(listingId: listing.id)

        try await service.acceptOffer(offerId: offerId)

        // Re-fetch and verify
        await service.fetchOffersForListing(listingId: listing.id)
        let match = service.offers.first { $0.id == offerId }
        XCTAssertEqual(match?.status, .accepted)
    }

    func testDeclineOffer() async throws {
        let listing = try await createTestListing(title: "Decline Offer Listing")
        let offerId = try await createTestOffer(listingId: listing.id, amount: 150)

        await service.fetchOffersForListing(listingId: listing.id)

        try await service.declineOffer(offerId: offerId)

        await service.fetchOffersForListing(listingId: listing.id)
        let match = service.offers.first { $0.id == offerId }
        XCTAssertEqual(match?.status, .declined)
    }

    func testWithdrawOffer() async throws {
        let listing = try await createTestListing(title: "Withdraw Offer Listing")
        let offerId = try await createTestOffer(listingId: listing.id, amount: 180)

        await service.fetchOffersForListing(listingId: listing.id)

        try await service.withdrawOffer(offerId: offerId)

        await service.fetchOffersForListing(listingId: listing.id)
        let match = service.offers.first { $0.id == offerId }
        XCTAssertEqual(match?.status, .withdrawn)
    }

    // MARK: - Transactions

    func testCreateShipTransaction() async throws {
        let listing = try await createTestListing(title: "Ship Tx Listing", price: 300)
        let fakeBuyerId = UUID()

        let transaction: MarketplaceTransaction
        do {
            transaction = try await createTestShipTransaction(
                listingId: listing.id, amount: 300, buyerId: fakeBuyerId
            )
        } catch {
            throw XCTSkip("Transaction INSERT blocked by RLS: \(error.localizedDescription)")
        }

        XCTAssertEqual(transaction.listingId, listing.id)
        XCTAssertEqual(transaction.buyerId, fakeBuyerId)
        XCTAssertEqual(transaction.sellerId, TestUser.id)
        XCTAssertEqual(transaction.transactionType, .ship)
        XCTAssertEqual(transaction.status, .pendingPayment)
        XCTAssertEqual(transaction.amount, 300)

        // Verify platform fee calculation (10%)
        let expectedFee = (Decimal(300) * MarketplaceService.platformFeePercentage)
        XCTAssertEqual(transaction.platformFee, expectedFee)
        XCTAssertEqual(transaction.sellerPayout, 300 - expectedFee)
    }

    func testCreateMeetupTransaction() async throws {
        let listing = try await createTestListing(title: "Meetup Tx Listing", price: 200)
        let fakeBuyerId = UUID()

        let transaction: MarketplaceTransaction
        do {
            transaction = try await service.createMeetupTransaction(
                listingId: listing.id,
                buyerId: fakeBuyerId,
                sellerId: TestUser.id,
                offerId: nil,
                amount: 200
            )
            trackForCleanup(table: "marketplace_transactions", id: transaction.id)
        } catch {
            throw XCTSkip("Transaction INSERT blocked by RLS: \(error.localizedDescription)")
        }

        XCTAssertEqual(transaction.transactionType, .meetup)
        XCTAssertEqual(transaction.status, .meetupScheduled)
        XCTAssertEqual(transaction.amount, 200)
        // Meetup transactions have no platform fee
        XCTAssertEqual(transaction.platformFee, 0)
        XCTAssertEqual(transaction.sellerPayout, 200)
    }

    func testTransactionLifecycle_ship() async throws {
        let listing = try await createTestListing(title: "Ship Lifecycle Listing", price: 350)
        let fakeBuyerId = UUID()

        let transaction: MarketplaceTransaction
        do {
            transaction = try await createTestShipTransaction(
                listingId: listing.id, amount: 350, buyerId: fakeBuyerId
            )
        } catch {
            throw XCTSkip("Transaction INSERT blocked by RLS: \(error.localizedDescription)")
        }

        // Mark as shipped (test user is the seller)
        try await service.markAsShipped(
            transactionId: transaction.id,
            trackingNumber: "TEST123456",
            carrier: "UPS"
        )

        // Fetch directly from DB to verify
        let shipped: MarketplaceTransaction = try await supabase
            .from("marketplace_transactions")
            .select()
            .eq("id", value: transaction.id.uuidString)
            .single()
            .execute()
            .value

        XCTAssertEqual(shipped.status, .shipped)
        XCTAssertEqual(shipped.trackingNumber, "TEST123456")
        XCTAssertEqual(shipped.trackingCarrier, "UPS")
        XCTAssertNotNil(shipped.shippedAt)

        // confirmReceipt requires buyer auth + Stripe payout — skip
    }

    func testTransactionLifecycle_meetup() async throws {
        let listing = try await createTestListing(title: "Meetup Lifecycle Listing", price: 250)
        let fakeBuyerId = UUID()

        let transaction: MarketplaceTransaction
        do {
            transaction = try await service.createMeetupTransaction(
                listingId: listing.id,
                buyerId: fakeBuyerId,
                sellerId: TestUser.id,
                offerId: nil,
                amount: 250
            )
            trackForCleanup(table: "marketplace_transactions", id: transaction.id)
        } catch {
            throw XCTSkip("Transaction INSERT blocked by RLS: \(error.localizedDescription)")
        }

        // Schedule meetup (test user is buyer or seller, both allowed)
        let meetupDate = Date().addingTimeInterval(86400)
        try await service.scheduleMeetup(
            transactionId: transaction.id,
            locationName: "Test Park, CA",
            lat: 37.77,
            lng: -122.42,
            scheduledAt: meetupDate
        )

        // Verify meetup details persisted
        let afterSchedule: MarketplaceTransaction = try await supabase
            .from("marketplace_transactions")
            .select()
            .eq("id", value: transaction.id.uuidString)
            .single()
            .execute()
            .value
        XCTAssertEqual(afterSchedule.meetupLocationName, "Test Park, CA")
        XCTAssertNotNil(afterSchedule.meetupScheduledAt)

        // Seller confirms meetup complete
        try await service.confirmMeetupComplete(
            transactionId: transaction.id,
            byUserId: TestUser.id
        )

        // Verify seller confirmed, but transaction NOT completed (needs buyer too)
        let afterConfirm: MarketplaceTransaction = try await supabase
            .from("marketplace_transactions")
            .select()
            .eq("id", value: transaction.id.uuidString)
            .single()
            .execute()
            .value
        XCTAssertNotNil(afterConfirm.sellerConfirmedAt)
        XCTAssertNil(afterConfirm.buyerConfirmedAt, "Buyer has not confirmed yet")
        XCTAssertNotEqual(afterConfirm.status, .meetupCompleted,
                          "Should not be completed until both parties confirm")
    }

    // MARK: - Reviews

    func testSubmitAndFetchReview() async throws {
        let listing = try await createTestListing(title: "Review Test Listing", price: 100)
        let fakeBuyerId = UUID()

        let transaction: MarketplaceTransaction
        do {
            transaction = try await createTestShipTransaction(
                listingId: listing.id, amount: 100, buyerId: fakeBuyerId
            )
        } catch {
            throw XCTSkip("Transaction needed for review test, blocked by RLS: \(error.localizedDescription)")
        }

        // Submit review from test user (seller) to fake buyer
        try await service.submitReview(
            transactionId: transaction.id,
            fromUserId: TestUser.id,
            toUserId: fakeBuyerId,
            rating: 5,
            comment: "Great buyer, quick payment!"
        )

        // Fetch reviews for the fake buyer to find ours
        let reviews = try await service.fetchReviewsForUser(userId: fakeBuyerId)
        let match = reviews.first { $0.review.transactionId == transaction.id }

        XCTAssertNotNil(match)
        XCTAssertEqual(match?.review.rating, 5)
        XCTAssertEqual(match?.review.comment, "Great buyer, quick payment!")
        XCTAssertEqual(match?.review.fromUserId, TestUser.id)

        if let reviewId = match?.id {
            trackForCleanup(table: "marketplace_reviews", id: reviewId)
        }
    }

    func testHasUserReviewed() async throws {
        let listing = try await createTestListing(title: "HasReviewed Test Listing", price: 100)
        let fakeBuyerId = UUID()

        let transaction: MarketplaceTransaction
        do {
            transaction = try await createTestShipTransaction(
                listingId: listing.id, amount: 100, buyerId: fakeBuyerId
            )
        } catch {
            throw XCTSkip("Transaction needed for review test, blocked by RLS: \(error.localizedDescription)")
        }

        // Before submitting a review
        let before = await service.hasUserReviewed(
            transactionId: transaction.id,
            userId: TestUser.id
        )
        XCTAssertFalse(before, "Should not have reviewed yet")

        // Submit review
        try await service.submitReview(
            transactionId: transaction.id,
            fromUserId: TestUser.id,
            toUserId: fakeBuyerId,
            rating: 4,
            comment: "Good transaction"
        )

        // After submitting
        let after = await service.hasUserReviewed(
            transactionId: transaction.id,
            userId: TestUser.id
        )
        XCTAssertTrue(after, "Should show as reviewed after submission")

        // Clean up review
        struct ReviewId: Decodable { let id: UUID }
        let createdReviews: [ReviewId] = try await supabase
            .from("marketplace_reviews")
            .select("id")
            .eq("transaction_id", value: transaction.id.uuidString)
            .eq("from_user_id", value: TestUser.id.uuidString)
            .execute()
            .value
        for r in createdReviews {
            trackForCleanup(table: "marketplace_reviews", id: r.id)
        }
    }

    // MARK: - RLS Policy Verification (CRITICAL)

    func testCannotCreateTransactionDirectly() async throws {
        // Attempt raw INSERT into marketplace_transactions where the auth user
        // is neither buyer nor seller — RLS should block it.
        let insert: [String: String] = [
            "listing_id": UUID().uuidString,
            "buyer_id": UUID().uuidString,
            "seller_id": UUID().uuidString,
            "transaction_type": "ship",
            "status": "pending_payment",
            "amount": "100",
            "platform_fee": "10",
            "seller_payout": "90"
        ]

        do {
            try await supabase
                .from("marketplace_transactions")
                .insert(insert)
                .execute()
            XCTFail("RLS should block INSERT when auth user is neither buyer nor seller")
        } catch {
            // Expected — RLS or FK constraint blocked the insert
        }
    }

    func testCannotUpdateTransactionDirectly() async throws {
        // Attempt to UPDATE a transaction where the auth user is not a participant.
        // Using a random UUID means RLS should filter the row out (0 rows affected).
        let fakeId = UUID()

        do {
            try await supabase
                .from("marketplace_transactions")
                .update(["status": "completed"])
                .eq("id", value: fakeId.uuidString)
                .execute()
            // PostgREST returns 200 with 0 rows — RLS silently filtered the row
        } catch {
            // RLS explicitly blocked the update — also acceptable
        }
    }

    func testCannotUpdateOtherUsersListing() async throws {
        // Verify that a listing INSERT with a different seller_id is blocked by RLS.
        let otherSellerId = UUID()
        let insert = MarketplaceListingInsert(
            sellerId: otherSellerId,
            title: "Should Be Blocked",
            description: "RLS test",
            price: 100,
            category: .drones,
            condition: .good,
            transactionType: .ship,
            imageUrls: [],
            locationName: nil,
            locationLat: nil,
            locationLng: nil,
            brand: nil,
            model: nil,
            shippingCost: nil
        )

        do {
            let response: [MarketplaceListing] = try await supabase
                .from("marketplace_listings")
                .insert(insert)
                .select()
                .execute()
                .value

            if let created = response.first {
                // If somehow created, clean it up and fail
                trackForCleanup(table: "marketplace_listings", id: created.id)
                XCTFail("RLS should block creating a listing with seller_id != auth user")
            }
            // Empty response means RLS silently blocked it
        } catch {
            // Expected — RLS blocked the insert
        }
    }
}
